# Generated by Django 5.2.3 on 2025-07-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0006_auto_20250707_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('deviation', 'order')},
        ),
    ]
