# Generated by Django 5.2.3 on 2025-07-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0008_action_action_responsible_users_and_more'),
    ]

    operations = [
    ]
