# Generated by Django 5.2.3 on 2025-07-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0009_auto_20250710_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_responsible_user',
        ),
    ]
