# Generated by Django 5.2.3 on 2025-07-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_column', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('dev_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_plant', models.CharField(blank=True, max_length=100, null=True)),
                ('affected_plant', models.CharField(blank=True, max_length=255, null=True)),
                ('sbu', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('effectivity_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('drawing_number', models.CharField(blank=True, max_length=255, null=True)),
                ('back_to_back_deviation', models.BooleanField(default=False)),
                ('defect_category', models.CharField(blank=True, max_length=100, null=True)),
                ('assembly_defect_type', models.CharField(blank=True, max_length=100, null=True)),
                ('molding_defect_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Deviations',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('action_responsible', models.CharField(max_length=100)),
                ('action_expiration_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('deviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='deviations.deviation')),
            ],
            options={
                'verbose_name_plural': 'Actions',
                'ordering': ['action_expiration_date'],
            },
        ),
    ]
