# Generated by Django 5.2.3 on 2025-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='deviation_attachments/'),
        ),
    ]
