# Generated by Django 5.2.3 on 2025-07-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0002_deviation_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Not Started', max_length=20),
        ),
    ]
